### ISSUE TITLE
Lot's of new links

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [valentinogagliardi/awesome-css-grid#4]
Hi @valentinogagliardi

To help you and after reading the [CONTRIBUTING.md](https://github.com/valentinogagliardi/awesome-css-grid/blob/master/CONTRIBUTING.md) I want to know if as you mention I can reorder links in alphabetical order from A to Z in a single PR and then and then add a new link after you accept the last link added via PR

Don't know if I'm explaining myself

**Comment by valentinogagliardi** [comment]
That would be great, go ahead!
